In [ ]:
# 움직이는 거북이 모듈생성

import time
from turtle import Turtle

john = Turtle()
print(john)
john.shape("turtle")
john.color("red", "green")
while True:
    john.forward(5)
    john.left(5)
    time.sleep(1)

In [6]:
# 파일을 쓰기 모드("w")로 엽니다.
with open("./test2.txt", "w") as f:
    # 파일에 내용을 쓰기
    f.write("Hello, this is test2.txt!\nSecond line.\nThird line.")

# 이후의 코드는 이전과 동일합니다.
f4 = open("./test2.txt", "r")
print(f4.read())
f4.seek(0)
print(f4.tell())
context = f4.readlines()
print(context)
f4.close()

Hello, this is test2.txt!
Second line.
Third line.
0
['Hello, this is test2.txt!\n', 'Second line.\n', 'Third line.']


In [20]:
info = []

for _ in range(3):
    text = input("아이디 비밀번호 ex) 유즈 123")
    info.append(text)
    
with open("./text.txt", "a") as f:
    for line in info:
        f.write(line + "\n")

In [18]:
# 실습 1
info = []

for _ in range(3):
    name = input("이름을 입력하세요")
    password = input("비밀번호를 입력하세요.")
    info.append({"name": name, "password": password})
    
    
with open("./member.txt", "a") as f:
    for user_info in info:
        f.write(f"{user_info['name']}:{user_info['password']}\n")

In [19]:
# 실습 2
login_name = input("이름을 입력하세요")
login_password = input("비밀번호를 입력하세요")

with open("./member.txt", "r") as f:
    for line in f:
        stored_name, stored_password = line.strip().split(":")
        if login_name == stored_name and login_password == stored_password:
            print("로그인 성공")
            break
    else:
        print("로그인 실패")
        



로그인 성공


In [ ]:
# 실습 3

info = []
login_name = input("이름을 입력하세요")
login_password = input("비밀번호를 입력하세요")

with open("./member.txt", "r") as f:
    for line in f:
        stored_name, stored_password = line.strip().split(":")
        if login_name == stored_name and login_password == stored_password:
            print("로그인 성공")
            number = input("전화번호를 입력하세요")
            for _ in range(1):
                info.append({"number": number})
            
            with open("./member.txt", "+") as f:
                for user_info in info:
                    f.write(f"{user_info['number']}\n")
        
        else:   
            print("로그인 실패")
            
            
           
    
   
            
            
           
        

In [ ]:
name = input("input name")
pw = input("input pw")
isLogin = False
with open("member.txt","r") as file:
  lines = file.readlines()
  file.seek(0)
  for line in lines:
    text = line.split()# [ name, pw ]
    if len(text) >= 2 and text[0] == name and text[1] == pw:
      isLogin= True
      break
if isLogin:
  print("log in")
else :
  print("log in failed")
if isLogin:
  telNum = input("input tel num")
  with open("member_tel.txt","r+") as file:
    lines = file.readlines()
    file.seek(0)
    for i, line in enumerate(lines): # mylist = ['A', 'B', 'C'] -> (0, 'A'), (1, 'B'), (2,'C')
      text = line.split()
      if text and text[0] == name:
        lines[i] = f"{name} {telNum}\n"
        break
    else:
      lines.append(f"{name} {telNum}\n")
    file.writelines(lines)

In [3]:
# 사용자가 제대로 된 정수를 입력할 때 까지 반복하여 입력 받기
while True:
    try:
        num = int(input('정수 입력'))
    except:
        print('정수가 아님! 정수를 입력해주세요!')
    else:
        print(f"정수 입력 성공 : {num}")
        break

정수가 아님! 정수를 입력해주세요!
정수 입력 성공 : 3


In [6]:
import numpy as np
x = np.array([3,1,2])
print(x)
type(x)

[3 1 2]


numpy.ndarray

In [5]:
#실습 1
import numpy as np
num1 = np.zeros(10)
print(num1)



[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [8]:

#실습 2
import numpy as np
num1 = np.zeros(10)
num1[4] = 1

print(num1)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [3]:
#실습 3
import numpy as np
num = np.arange(10,31)
print(num)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30]


In [23]:
#실습 4
import numpy as np


n4 = np.random.randint(0,100, size=(2,2))
print(n4)

[[74  2]
 [43 25]]


In [21]:
#실습 5
import numpy as np

n5 = np.random.rand(2,4)
print(n5)

[[0.67126433 0.73433915 0.09105149 0.29930283]
 [0.63027067 0.68968599 0.16239223 0.50011954]]


In [13]:
#실습 6
import numpy as np
n6 = np.arange(35,75)
n6.shape=(10,4)

print(n6)

[[35 36 37 38]
 [39 40 41 42]
 [43 44 45 46]
 [47 48 49 50]
 [51 52 53 54]
 [55 56 57 58]
 [59 60 61 62]
 [63 64 65 66]
 [67 68 69 70]
 [71 72 73 74]]


In [14]:
import numpy as np
n6 = np.arange(35,75)
n6.shape=(10,4)
n7 = n6[::-1]

print(n7)

[[71 72 73 74]
 [67 68 69 70]
 [63 64 65 66]
 [59 60 61 62]
 [55 56 57 58]
 [51 52 53 54]
 [47 48 49 50]
 [43 44 45 46]
 [39 40 41 42]
 [35 36 37 38]]


In [2]:
#실습 1
import numpy as np
a = np.array = [1,1,2,3,4,5,5,5,5,7,8,9,10,11,24,100]
unique_a = np.unique(a)
print(unique_a)

[  1   2   3   4   5   7   8   9  10  11  24 100]


In [12]:
#실습 2
import numpy as np
a = np.array = [1,1,2,3,4,5,5,5,5,7,8,9,10,11,24,100]
unique_a = np.unique(a)

np.max(unique_a)
np.min(unique_a)
np.mean(unique_a)
#실습 3
np.sum(unique_a)



184

In [1]:
#실습 4
import numpy as np
a = np.array = [1,1,2,3,4,5,5,5,5,7,8,9,10,11,24,100]
b = np.sort(a)

np.median(b)



5.0